packages:
  - ./demo/*
  - ./docs
  - ./packages/*
  - ./tests/*

ignoredBuiltDependencies:
  - '@biomejs/biome'

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - canvas
  - esbuild
  - sharp
  - workerd
