packages:
  - ./demo
  - ./demo/cloudflare
  - ./demo/browser
  - ./demo/waku
  - ./demo/express
  - ./demo/visualization
  - ./demo/trace-events
  - ./docs
  - ./packages/*
  - ./tests/*

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
  - workerd
