packages:
  - ./demo
  - ./demo/cloudflare
  - ./demo/browser
  - ./demo/waku
  - ./docs
  - ./packages/*
  - ./tests/*

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
  - workerd
